-- =====================================================================
-- Avance 1 - Base de Datos 2 (Septiembre 2026)
-- Grupo 5 - Subsistema Tripulación - PostgreSQL 16
-- =====================================================================

SET client_min_messages = warning;   -- oculta avisos "does not exist, skipping" en la primera ejecución

DROP TABLE IF EXISTS asignacion_tripulacion, jornada_laboral, licencia_medica,
                     certificacion, vuelo, tripulante, hub, aeropuerto, region CASCADE;
DROP FUNCTION IF EXISTS fn_validar_asignacion() CASCADE;


-- ---------------------------------------------------------------------
-- TABLAS COMUNES A TODOS LOS GRUPOS
-- ---------------------------------------------------------------------

-- Región: exactamente 3 valores posibles.
CREATE TABLE region (
    id_region      SMALLINT     PRIMARY KEY,
    nombre_region  VARCHAR(10)  NOT NULL UNIQUE
        CHECK (nombre_region IN ('ESTE', 'CENTRAL', 'OESTE'))
);

-- Aeropuerto: cualquier lugar donde la aerolínea aterriza.
CREATE TABLE aeropuerto (
    id_aeropuerto  INTEGER      PRIMARY KEY,
    id_region      SMALLINT     NOT NULL REFERENCES region (id_region),
    codigo_iata    CHAR(3)      NOT NULL UNIQUE
        CHECK (codigo_iata IN (
            -- Este
            'CLT','PHL','JFK','LGA','DCA','MIA','BOS','EWR','BWI','IAD','PIT','RDU','ATL','MCO',
            -- Central
            'DFW','ORD','MSP','DTW','CLE','STL','MCI','MSY','IAH','AUS','SAT','MEM','BNA','MDW',
            -- Oeste
            'PHX','LAX','SFO','SAN','LAS','SEA','PDX','SLC','DEN','ABQ','TUS','SJC','SNA','OAK')),
    nombre         VARCHAR(100) NOT NULL,
    ciudad         VARCHAR(60)  NOT NULL,
    estado         CHAR(2)      NOT NULL          -- estado de EE. UU. (TX, NY, ...)
);

-- Hub: aeropuerto que además es base de operaciones.
CREATE TABLE hub (
    id_hub                  SMALLINT  PRIMARY KEY,
    id_aeropuerto           INTEGER   NOT NULL UNIQUE REFERENCES aeropuerto (id_aeropuerto),
    fecha_inicio_operacion  DATE      NOT NULL
);


-- ---------------------------------------------------------------------
-- SUBSISTEMA TRIPULACIÓN
-- ---------------------------------------------------------------------

-- Tripulante: personal de cabina de mando y de cabina de pasajeros.
CREATE TABLE tripulante (
    id_tripulante     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_nacimiento  DATE         NOT NULL,
    fecha_ingreso     DATE         NOT NULL,
    id_hub_base       SMALLINT     NOT NULL REFERENCES hub (id_hub),
    numero_empleado   CHAR(8)      NOT NULL UNIQUE,              -- p. ej. AA004512
    nombre            VARCHAR(50)  NOT NULL,
    apellido          VARCHAR(50)  NOT NULL,
    cargo             VARCHAR(20)  NOT NULL
        CHECK (cargo IN ('PILOTO', 'COPILOTO', 'JEFE_CABINA', 'AUXILIAR_VUELO')),
    estado            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVO'
        CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CHECK (fecha_ingreso >= fecha_nacimiento + INTERVAL '18 years')   -- mayor de edad al ingresar
);

-- Certificación: habilitaciones y cursos obligatorios de cada tripulante (1 tripulante : N certificaciones).
CREATE TABLE certificacion (
    id_certificacion    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tripulante       BIGINT       NOT NULL REFERENCES tripulante (id_tripulante),
    fecha_emision       DATE         NOT NULL,
    fecha_vencimiento   DATE         NOT NULL,
    numero_certificado  CHAR(10)     NOT NULL UNIQUE,
    tipo_certificacion  VARCHAR(30)  NOT NULL
        CHECK (tipo_certificacion IN ('LICENCIA_ATP', 'HABILITACION_TIPO', 'CRM',
                                      'SEGURIDAD_CABINA', 'PRIMEROS_AUXILIOS', 'MERCANCIAS_PELIGROSAS')),
    estado              VARCHAR(20)  NOT NULL
        CHECK (estado IN ('VIGENTE', 'VENCIDA', 'SUSPENDIDA')),
    CHECK (fecha_vencimiento > fecha_emision)
);

-- Licencia médica: certificado médico aeronáutico que el tripulante debe tener vigente para volar.
-- Clase 1: cabina de mando (PILOTO, COPILOTO). Clase 2: cabina de pasajeros (JEFE_CABINA, AUXILIAR_VUELO).
CREATE TABLE licencia_medica (
    id_licencia        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tripulante      BIGINT       NOT NULL REFERENCES tripulante (id_tripulante),
    fecha_emision      DATE         NOT NULL,
    fecha_vencimiento  DATE         NOT NULL,
    numero_licencia    CHAR(10)     NOT NULL UNIQUE,
    clase_medica       CHAR(1)      NOT NULL
        CHECK (clase_medica IN ('1', '2')),
    restricciones      VARCHAR(60)  NOT NULL DEFAULT 'NINGUNA',
    estado             VARCHAR(20)  NOT NULL
        CHECK (estado IN ('VIGENTE', 'VENCIDA', 'SUSPENDIDA')),
    CHECK (fecha_vencimiento > fecha_emision)
);

-- Jornada laboral: un día de servicio de un tripulante (máximo 14 h, una jornada por día).
CREATE TABLE jornada_laboral (
    id_jornada      BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tripulante   BIGINT        NOT NULL REFERENCES tripulante (id_tripulante),
    hora_inicio     TIMESTAMP     NOT NULL,
    hora_fin        TIMESTAMP     NOT NULL,
    fecha_jornada   DATE          NOT NULL,
    horas_servicio  NUMERIC(4,2)  GENERATED ALWAYS AS
                        (ROUND(EXTRACT(EPOCH FROM (hora_fin - hora_inicio)) / 3600, 2)) STORED,
    tipo_jornada    VARCHAR(20)   NOT NULL
        CHECK (tipo_jornada IN ('VUELO', 'RESERVA', 'ENTRENAMIENTO')),
    CHECK (hora_fin > hora_inicio),
    CHECK (hora_fin - hora_inicio <= INTERVAL '14 hours'),
    CHECK (fecha_jornada = hora_inicio::date),
    UNIQUE (id_tripulante, fecha_jornada)
);

-- Vuelo: versión propia y simplificada de los vuelos que opera la tripulación
CREATE TABLE vuelo (
    id_vuelo               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_salida_real      TIMESTAMP    NOT NULL,
    fecha_llegada_real     TIMESTAMP    NOT NULL,
    id_aeropuerto_origen   INTEGER      NOT NULL REFERENCES aeropuerto (id_aeropuerto),
    id_aeropuerto_destino  INTEGER      NOT NULL REFERENCES aeropuerto (id_aeropuerto),
    retraso_minutos        INTEGER      NOT NULL DEFAULT 0 CHECK (retraso_minutos >= 0),
    numero_vuelo           CHAR(6)      NOT NULL,                  -- p. ej. AA1234
    estado                 VARCHAR(20)  NOT NULL
        CHECK (estado IN ('COMPLETADO', 'DESVIADO')),
    CHECK (fecha_llegada_real > fecha_salida_real),                -- no aterriza antes de despegar
    CHECK (id_aeropuerto_origen <> id_aeropuerto_destino)
);

-- Asignación de tripulación: tabla de MAYOR VOLUMEN (>= 5.000 registros).
-- Atributos obligatorios del enunciado: id_asignacion BIGINT, id_tripulante BIGINT,
-- rol VARCHAR(20), horas_vuelo NUMERIC(5,2), fecha_asignacion DATE.
CREATE TABLE asignacion_tripulacion (
    id_asignacion     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tripulante     BIGINT        NOT NULL REFERENCES tripulante (id_tripulante),
    id_vuelo          BIGINT        NOT NULL REFERENCES vuelo (id_vuelo),
    fecha_asignacion  DATE          NOT NULL,
    horas_vuelo       NUMERIC(5,2)  NOT NULL CHECK (horas_vuelo > 0),
    rol               VARCHAR(20)   NOT NULL
        CHECK (rol IN ('PILOTO', 'COPILOTO', 'JEFE_CABINA', 'AUXILIAR_VUELO'))
);


-- ---------------------------------------------------------------------
-- REGLAS DE NEGOCIO QUE NO SE PUEDEN EXPRESAR CON CHECK (trigger)
-- ---------------------------------------------------------------------
-- Al insertar o modificar una asignación:
--   1. Un tripulante no puede estar asignado a dos vuelos que se crucen en horario
--      (también impide asignarlo dos veces al mismo vuelo).
--   2. El rol en el vuelo debe coincidir con el cargo del tripulante.
--   3. Debe tener un certificado médico vigente de la clase que exige su rol
--      durante todo el vuelo (clase 1 cabina de mando, clase 2 cabina de pasajeros).
--   4. La asignación se hace el día del vuelo o antes.
--   5. horas_vuelo se calcula siempre como la duración real del vuelo.
CREATE FUNCTION fn_validar_asignacion() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_salida   TIMESTAMP;
    v_llegada  TIMESTAMP;
    v_cargo    VARCHAR(20);
    v_clase    CHAR(1);
BEGIN
    SELECT fecha_salida_real, fecha_llegada_real
      INTO v_salida, v_llegada
      FROM vuelo
     WHERE id_vuelo = NEW.id_vuelo;

    SELECT cargo INTO v_cargo
      FROM tripulante
     WHERE id_tripulante = NEW.id_tripulante;

    IF NEW.rol <> v_cargo THEN
        RAISE EXCEPTION 'El rol % no coincide con el cargo % del tripulante %',
                        NEW.rol, v_cargo, NEW.id_tripulante;
    END IF;

    IF EXISTS (
        SELECT 1
          FROM asignacion_tripulacion a
          JOIN vuelo v ON v.id_vuelo = a.id_vuelo
         WHERE a.id_tripulante = NEW.id_tripulante
           AND a.id_asignacion <> NEW.id_asignacion
           AND v.fecha_salida_real  < v_llegada
           AND v.fecha_llegada_real > v_salida
    ) THEN
        RAISE EXCEPTION 'Tripulante % ya tiene un vuelo que se cruza con el vuelo %',
                        NEW.id_tripulante, NEW.id_vuelo;
    END IF;

    v_clase := CASE WHEN NEW.rol IN ('PILOTO', 'COPILOTO') THEN '1' ELSE '2' END;

    IF NOT EXISTS (
        SELECT 1
          FROM licencia_medica l
         WHERE l.id_tripulante = NEW.id_tripulante
           AND l.clase_medica = v_clase
           AND l.estado <> 'SUSPENDIDA'
           AND l.fecha_emision <= v_salida::date
           AND l.fecha_vencimiento >= v_llegada::date
    ) THEN
        RAISE EXCEPTION 'Tripulante % no tiene certificado médico clase % vigente para el vuelo %',
                        NEW.id_tripulante, v_clase, NEW.id_vuelo;
    END IF;

    IF NEW.fecha_asignacion > v_salida::date THEN
        RAISE EXCEPTION 'La asignación (%) no puede ser posterior a la salida del vuelo (%)',
                        NEW.fecha_asignacion, v_salida::date;
    END IF;

    NEW.horas_vuelo := ROUND(EXTRACT(EPOCH FROM (v_llegada - v_salida)) / 3600, 2);
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validar_asignacion
BEFORE INSERT OR UPDATE ON asignacion_tripulacion
FOR EACH ROW EXECUTE FUNCTION fn_validar_asignacion();


-- ---------------------------------------------------------------------
-- DOCUMENTACIÓN
-- ---------------------------------------------------------------------
COMMENT ON TABLE region                 IS 'Región geográfica: ESTE, CENTRAL u OESTE.';
COMMENT ON TABLE aeropuerto             IS 'Aeropuertos donde aterriza la aerolínea (42 del enunciado).';
COMMENT ON TABLE hub                    IS 'Aeropuertos que son base de operaciones (10 del enunciado).';
COMMENT ON TABLE tripulante             IS 'Pilotos, copilotos, jefes de cabina y auxiliares de vuelo.';
COMMENT ON TABLE certificacion          IS 'Certificaciones y habilitaciones de cada tripulante.';
COMMENT ON TABLE licencia_medica        IS 'Certificados médicos aeronáuticos (clase 1 y 2) requeridos para volar.';
COMMENT ON TABLE jornada_laboral        IS 'Jornadas de servicio diarias (máx. 14 h).';
COMMENT ON TABLE vuelo                  IS 'Vuelos operados (versión propia del subsistema).';
COMMENT ON TABLE asignacion_tripulacion IS 'Asignación de tripulantes a vuelos. Tabla de mayor volumen.';


-- ---------------------------------------------------------------------
-- VERIFICACIÓN: debe listar 9 tablas y solo índices de PK/UNIQUE
-- ---------------------------------------------------------------------
SELECT tablename, indexname, indexdef
FROM pg_indexes
WHERE schemaname = 'public'
ORDER BY tablename, indexname;
